- name: download redis sources
  get_url: url=http://download.redis.io/releases/redis-3.2.8.tar.gz dest=/tmp/redis-3.2.8.tar.gz

- name: create redis dir.
  file:
    path: /opt/redis
    state: directory
    mode: 0644

- name: unzipping archive
  unarchive:
    src: /tmp/redis-3.2.8.tar.gz
    dest: /opt/
    copy: no

- name: making redis.
  command: make
  args:
    chdir: /opt/redis-3.2.8