- hosts: freshvm
  serial: 1
  remote_user: root

  vars: 
    createuser: 'ansibleremote'
    createpassword: 'myamazingpassword'

  tasks:

  - name: Setup | create user
    command: useradd -m {{ createuser }} creates=/home/{{ createuser }}
    sudo: true

  - name: Setup | set user password
    shell: usermod -p $(echo '{{ createpassword }}' | openssl passwd -1 -stdin) {{ createuser }}
    sudo: true 

  - name: Setup | authorized key upload
    authorized_key: user={{ createuser }}
      key="{{ lookup('file', '../ansible_id_rsa.pub') }}"
      path='/home/{{ createuser }}/.ssh/authorized_keys'
      manage_dir=no
    sudo: true


  - name: Sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers
      insertafter=EOF
      line='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
      regexp='{{ createuser }} ALL=(ALL) NOPASSWD: ALL'
      state=present"
    sudo: true


  - name: Setup networking (interfaces)
    lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-ens3
        state: present
        regexp: '^IPADDR="192.168.1.100"'
        line: 'IPADDR="192.168.1.30"'

  - name: Stopping the new gateway
    command: shutdown -r now